const tseslint = require("typescript-eslint");

module.exports = [
  // plugin + parser
  tseslint.configs.base,

  // parser option for typescript-eslint for the TypeChecked rules
  {
    name: "eslint-config-pv/ts-plugin-options",
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.json",
        // expecting users tsconfig in the same directory as where eslint is executed. (i.e. root)
        tsconfigRootDir: process.cwd(),
      },
    },
  },

  // disable all rules known to conflict with @typescript-eslint plugin
  // all have an equivalent @typescript-eslint/ rule.
  // {@see https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/src/configs}
  {
    name: "eslint-config-pv/ts-reset-rules",
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "default-param-last": "off",
      "dot-notation": "off",
      "init-declarations": "off",
      "no-array-constructor": "off",
      "no-dupe-class-members": "off",
      "no-empty-function": "off",
      "no-implied-eval": "off",
      "no-invalid-this": "off",
      "no-loop-func": "off",
      "no-magic-numbers": "off",
      "no-redeclare": "off",
      "no-restricted-imports": "off",
      "no-shadow": "off",
      // disables for @typescript-eslint/only-throw-error, which used to be called @typescript-eslint/no-throw-literal
      "no-throw-literal": "off",
      "no-unused-expressions": "off",
      "no-unused-vars": "off",
      "no-use-before-define": "off",
      "no-useless-constructor": "off",
      "prefer-promise-reject-errors": "off",
      "require-await": "off",
      "class-methods-use-this": "off",
      "no-return-await": "off",
      "consistent-return": "off",
      "max-params": "off",
      "prefer-destructuring": "off",
    },
  },

  // @typescript-eslint rules
  {
    name: "eslint-config-pv/ts-rules",
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "@typescript-eslint/adjacent-overload-signatures": "error",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/ban-tslint-comment": "off",
      "@typescript-eslint/class-literal-property-style": "off",
      "@typescript-eslint/consistent-indexed-object-style": "off",
      "@typescript-eslint/consistent-type-assertions": "error",
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/consistent-type-imports": "off",
      "@typescript-eslint/default-param-last": "off",
      "@typescript-eslint/dot-notation": "off",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-member-accessibility": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/init-declarations": "off",
      "@typescript-eslint/member-ordering": "off",
      "@typescript-eslint/method-signature-style": "off",
      "@typescript-eslint/naming-convention": "off",
      "@typescript-eslint/no-array-constructor": ["error"],
      "@typescript-eslint/no-base-to-string": "error",
      "@typescript-eslint/no-confusing-non-null-assertion": "off",
      "@typescript-eslint/no-confusing-void-expression": "off",
      "@typescript-eslint/no-dupe-class-members": ["error"],
      "@typescript-eslint/no-dynamic-delete": "off",
      "@typescript-eslint/no-empty-function": ["error"],
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-extra-non-null-assertion": "error",
      "@typescript-eslint/no-extraneous-class": "off",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-for-in-array": "error",
      "@typescript-eslint/no-implied-eval": ["error"],
      // lax to allow consistent type definition for all class's properties for example
      // independent of them having a default value or not
      "@typescript-eslint/no-inferrable-types": ["error", { ignoreParameters: true, ignoreProperties: true }],
      "@typescript-eslint/no-invalid-this": "off",
      "@typescript-eslint/no-invalid-void-type": "off",
      "@typescript-eslint/no-loop-func": "off",
      "@typescript-eslint/no-magic-numbers": ["off"],
      "@typescript-eslint/no-misused-new": "error",
      "@typescript-eslint/no-misused-promises": ["error", {
        // allow e.g. btn.addEventListener("click", async e => {...})
        checksVoidReturn: false,
      }],
      "@typescript-eslint/no-namespace": "error",
      "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
      // no additional linting when the developer has decided to use non null assertion
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-redeclare": "off",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-shadow": "off",
      "@typescript-eslint/no-this-alias": "error",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "off",
      "@typescript-eslint/no-unnecessary-condition": "off",
      "@typescript-eslint/no-unnecessary-qualifier": "off",
      "@typescript-eslint/no-unnecessary-type-arguments": "off",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      "@typescript-eslint/no-unnecessary-type-constraint": "off",
      "@typescript-eslint/no-unsafe-assignment": "error",
      // same as in @typescript-eslint/no-unsafe-member-access
      "@typescript-eslint/no-unsafe-call": "off",
      // lax usage of class members which are defined as any
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unused-expressions": ["error"],
      "@typescript-eslint/no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
      "@typescript-eslint/no-use-before-define": ["warn", {
        "functions": false,
        "classes": false,
      }],
      "@typescript-eslint/no-useless-constructor": ["error"],
      "@typescript-eslint/non-nullable-type-assertion-style": "off",
      "@typescript-eslint/prefer-as-const": "off",
      "@typescript-eslint/prefer-enum-initializers": "off",
      "@typescript-eslint/prefer-for-of": "off",
      "@typescript-eslint/prefer-function-type": "off",
      "@typescript-eslint/prefer-includes": "off",
      "@typescript-eslint/prefer-literal-enum-member": "off",
      "@typescript-eslint/prefer-namespace-keyword": "error",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      "@typescript-eslint/prefer-optional-chain": "off",
      "@typescript-eslint/prefer-readonly": "off",
      "@typescript-eslint/prefer-readonly-parameter-types": "off",
      "@typescript-eslint/prefer-reduce-type-parameter": "off",
      "@typescript-eslint/prefer-regexp-exec": "off",
      "@typescript-eslint/prefer-string-starts-ends-with": "off",
      "@typescript-eslint/promise-function-async": "off",
      "@typescript-eslint/require-array-sort-compare": "off",
      "@typescript-eslint/require-await": ["error"],
      // allow mixing types. e.g. age + " years"
      "@typescript-eslint/restrict-plus-operands": "off",
      // allow non string variables in template literal e.g. `is active: ${active}`
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/return-await": "off",
      "@typescript-eslint/strict-boolean-expressions": "off",
      "@typescript-eslint/switch-exhaustiveness-check": "off",
      "@typescript-eslint/triple-slash-reference": "error",
      "@typescript-eslint/typedef": "off",
      "@typescript-eslint/unbound-method": "error",
      "@typescript-eslint/unified-signatures": "off",
      "@typescript-eslint/consistent-type-exports": "off",
      "@typescript-eslint/no-meaningless-void-operator": "off",
      "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "off",
      "@typescript-eslint/no-restricted-imports": "off",
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/prefer-return-this-type": "off",
      "@typescript-eslint/consistent-generic-constructors": "off",
      "@typescript-eslint/no-duplicate-enum-values": "off",
      "@typescript-eslint/parameter-properties": "off",
      "@typescript-eslint/no-redundant-type-constituents": "off",
      "@typescript-eslint/no-useless-empty-export": "off",
      "@typescript-eslint/no-duplicate-type-constituents": "error",
      "@typescript-eslint/no-import-type-side-effects": "off",
      "@typescript-eslint/no-mixed-enums": "off",
      "@typescript-eslint/no-unsafe-declaration-merging": "error",
      "@typescript-eslint/no-unsafe-enum-comparison": "error",
      "@typescript-eslint/no-array-delete": "error",
      "@typescript-eslint/no-unsafe-unary-minus": "error",
      "@typescript-eslint/only-throw-error": "error",
      // allow using reject with only errors as argument unless `reject()`
      "@typescript-eslint/prefer-promise-reject-errors": ["error", {"allowEmptyReject": true}],
      "@typescript-eslint/class-methods-use-this": "off",
      "@typescript-eslint/consistent-return": "off",
      // same as in the ES config, but the @typescript-eslint rule ignore the `this` in the params
      "@typescript-eslint/max-params": ["warn", { "max": 4 }],
      "@typescript-eslint/no-deprecated": "warn",
      "@typescript-eslint/no-empty-object-type": "error",
      "@typescript-eslint/no-misused-spread": "error",
      "@typescript-eslint/no-restricted-types": "off",
      "@typescript-eslint/no-unnecessary-parameter-property-assignment": "off",
      "@typescript-eslint/no-unnecessary-template-expression": "error",
      "@typescript-eslint/no-unnecessary-type-parameters": "off",
      "@typescript-eslint/no-unsafe-function-type": "error",
      "@typescript-eslint/no-unsafe-type-assertion": "off",
      "@typescript-eslint/no-wrapper-object-types": "error",
      "@typescript-eslint/prefer-destructuring": "off",
      "@typescript-eslint/prefer-find": "off",
      "@typescript-eslint/related-getter-setter-pairs": "warn",
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "off",
    }
  }
];
