// list of eslint rules newer that 4.x and es6 rules which aren't provided in other files already,
// including eslint:recommended rules
module.exports = {
  "rules": {
    "default-case-last": "off",
    "default-param-last": "off",
    "function-call-argument-newline": "off",
    "grouped-accessor-pairs": "off",
    "id-denylist": "off",
    "implicit-arrow-linebreak": "off",
    "jsx-quotes": "off",
    "keyword-spacing": "off",
    "lines-between-class-members": "off",
    "max-classes-per-file": "off",
    "max-lines-per-function": "off",
    "multiline-comment-style": "off",
    "no-async-promise-executor": "error",
    "no-constructor-return": "off",
    "no-dupe-else-if": "error",
    "no-import-assign": "error",
    "no-loss-of-precision": "off",
    "no-misleading-character-class": "error",
    "no-multi-assign": "off",
    "no-nonoctal-decimal-escape": "off",
    "no-promise-executor-return": "off",
    "no-restricted-exports": "off",
    "no-restricted-properties": "off",
    "no-restricted-syntax": "off",
    "no-return-await": "off",
    "no-setter-return": "error",
    "no-unreachable-loop": "off",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "off",
    "no-unused-private-class-members": "off",
    "no-useless-backreference": "off",
    "no-useless-catch": "error",
    "prefer-exponentiation-operator": "off",
    "prefer-named-capture-group": "off",
    "prefer-object-spread": "off",
    "prefer-regex-literals": "off",
    "require-atomic-updates": "off",
    "require-unicode-regexp": "off",
    "sort-keys": "off",
    "no-constant-binary-expression": "off",
    "prefer-object-has-own": "off",
  }
};