// disable all rules known to conflict with @typescript-eslint plugin
// all have an equivalent @typescript-eslint/ rule.
// {@see https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin/src/configs}
module.exports = {
  rules: {
    "default-param-last": "off",
    "dot-notation": "off",
    "func-call-spacing": "off",
    "init-declarations": "off",
    "no-array-constructor": "off",
    "no-dupe-class-members": "off",
    "no-duplicate-imports": "off",
    "no-empty-function": "off",
    "no-implied-eval": "off",
    "no-invalid-this": "off",
    "no-loop-func": "off",
    "no-loss-of-precision": "off",
    "no-magic-numbers": "off",
    "no-redeclare": "off",
    "no-restricted-imports": "off",
    "no-shadow": "off",
    "no-throw-literal": "off",
    "no-unused-expressions": "off",
    "no-unused-vars": "off",
    "no-use-before-define": "off",
    "prefer-promise-reject-errors": "off",
    "no-useless-constructor": "off",
    "require-await": "off",
    "class-methods-use-this": "off",
    "no-return-await": "off",
    "consistent-return": "off",
    "max-params": "off",
    "prefer-destructuring": "off",
  },
};
